blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/MunyayLLC/https-github.com-joe10832-onchaintestkit/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 📚 Documentation
    url: https://github.com/MunyayLLC/https-github.com-joe10832-onchaintestkit#readme
    about: Read the project documentation and examples