name: Setup Issues
description: Report issues with development environment setup
title: "[Setup] "
labels: ["setup", "documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a setup issue! Please provide details to help us improve the copilot setup process.

  - type: checkboxes
    id: setup-steps
    attributes:
      label: Setup Steps Attempted
      description: Which setup steps have you tried?
      options:
        - label: Ran `npm install` 
        - label: Ran `npm run build`
        - label: Ran `npm run lint`
        - label: Ran `npm run test`
        - label: Ran `npm run copilot:setup`
        - label: Ran `npm run copilot:validate`
        - label: Prepared wallet extensions (`npm run prepare-metamask`)

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment are you using?
      options:
        - GitHub Codespaces
        - Local development
        - GitHub Actions
        - Docker
        - Other

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using? (run `node --version`)
      placeholder: "v18.17.0"
    validations:
      required: true

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: Please paste the complete error output
      render: shell
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: checkboxes
    id: documentation
    attributes:
      label: Documentation Checked
      description: Have you checked the relevant documentation?
      options:
        - label: Read `.github/copilot-instructions.md`
        - label: Checked `AGENTS.md` for general instructions
        - label: Reviewed the README setup section
        - label: Looked at the setup scripts in `/scripts` directory

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.