name: Development Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run Biome linter
      run: npm run lint
      
    - name: Check format
      run: npm run format
      continue-on-error: true  # Extension files may cause format errors
      
    - name: Lint fix (if needed)
      run: npm run lint:fix
      continue-on-error: true

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: lint-and-format
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build TypeScript
      run: npm run build
      
    - name: Run Playwright tests
      run: npm test
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-results
        path: test-results/
        retention-days: 7

  wallet-preparation:
    name: Wallet Extensions
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Prepare MetaMask (working)
      run: npm run prepare-metamask
      
    - name: Prepare Coinbase (broken - testing fix)
      run: npm run prepare-coinbase
      continue-on-error: true
      
    - name: Prepare Phantom (broken - testing fix)  
      run: npm run prepare-phantom
      continue-on-error: true
      
    - name: Check extension artifacts
      run: |
        echo "=== Extension Preparation Results ==="
        if [ -d "e2e/extensions" ]; then
          ls -la e2e/extensions/
        else
          echo "No extensions directory found"
        fi