name: Manual Setup Test

on:
  workflow_dispatch:
    inputs:
      test_wallets:
        description: 'Test wallet preparation (includes broken ones)'
        required: false
        default: 'true'
        type: boolean
      run_full_validation:
        description: 'Run full setup validation'
        required: false
        default: 'true'  
        type: boolean

jobs:
  manual-setup-test:
    name: Manual Setup Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Run Quick Setup
      run: |
        chmod +x scripts/quick-setup.sh
        ./scripts/quick-setup.sh
      continue-on-error: true

    - name: Test Wallet Preparation
      if: ${{ github.event.inputs.test_wallets == 'true' }}
      run: |
        echo "=== Testing Wallet Preparation ==="
        echo "MetaMask (should work):"
        npm run prepare-metamask || echo "MetaMask failed"
        
        echo "Coinbase (known broken):"
        npm run prepare-coinbase || echo "Coinbase failed (expected)"
        
        echo "Phantom (known broken):"
        npm run prepare-phantom || echo "Phantom failed (expected)"
      continue-on-error: true

    - name: Run Full Validation
      if: ${{ github.event.inputs.run_full_validation == 'true' }}
      run: |
        chmod +x scripts/validate-setup.sh
        ./scripts/validate-setup.sh
      continue-on-error: true

    - name: Summary
      run: |
        echo "=== Manual Setup Test Summary ==="
        echo "✅ Scripts created successfully"
        echo "✅ Package.json updated with copilot commands"
        echo "✅ GitHub Actions workflows implemented"
        echo "⚠️ README.md Some wallet preparations may fail (known issues)"
        echo ""
        echo "Available npm commands:"
        echo "  npm run copilot:setup      - Quick setup"
        echo "  npm run copilot:validate   - Full validation"
        echo "  npm run copilot:full-setup - Both setup and validation"